//tealium universal tag - utag.994 ut4.0.202603100458, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//www.redditstatic.com/ads/pixel.js"
};var w=window,wut=w.utag_data=w.utag_data||{};var brandArray=['news','adv','tcm','dtm','hwt'];var siteLookup={'news':'t2_smep16zy','adv':'t2_vrvyp68i','tcm':'t2_vrvj1a38','dtm':'t2_vrv8youl','hwt':'t2_vrvmwxuz','supercoach':'t2_tgr1fjm3'};var redditID="";for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
console.warn("Starting Reddit Pixel Initialization");!function(w,d){if(!w.rdt){var p=w.rdt=function(){p.sendEvent?p.sendEvent.apply(p,arguments):p.callQueue.push(arguments)};p.callQueue=[];}}(window,document);u.loader_cb=function(){u.initialized=true;console.warn("Reddit Pixel Initialized.Initializing Tracking");if(window.location.hostname.indexOf('supercoach')!==-1){redditId=siteLookup['supercoach'];}
else{redditId=siteLookup[wut.net_site];}
console.warn("Reddit Pixel Id Set:"+redditId);rdt('init',redditId,{"optOut":false,"useDecimalCurrencyValues":true});rdt('track','PageVisit');console.warn("Reddit PageVisit Tracking Executed");};if((window.location.hostname.indexOf('supercoach')!==-1)||(brandArray.indexOf(wut.net_site)!==-1)){if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_994'});}
else{u.loader_cb();}}
}};utag.o[loader].loader.LOAD(id);})("994","newsltd.gea");}catch(error){utag.DB(error);}
