//tealium universal tag - utag.sync ut4.0.202603100458, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{try{(function(){'use strict';var Logger=function(name){this.name=name;this.info=function(){if(window.console)console.info('[INFO]['+this.name+']',...arguments);};this.warn=function(){if(window.console)console.warn('[WARN]['+this.name+']',...arguments);};this.error=function(){if(window.console)console.error('[ERROR]['+this.name+']',...arguments);};};var Cookies={getCookie:function(name){var match=document.cookie.match(new RegExp('(^| )'+name+'=([^;]+)'));return match?decodeURIComponent(match[2]):null;}};var Storage={setLocalStorageItem:function(key,value){try{localStorage.setItem(key,value);}catch(e){}},getLocalStorageItem:function(key){try{return localStorage.getItem(key);}catch(e){return null;}}};var getParsedJwt=function(token){try{var base64Url=token.split('.')[1];var base64=base64Url.replace(/-/g,'+').replace(/_/g,'/');var jsonPayload=decodeURIComponent(atob(base64).split('').map(function(c){return'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2);}).join(''));return JSON.parse(jsonPayload);}catch(e){return{};}};(async function UserSubscriberData(){var logger=new Logger('UserMemtype');var rampartToken=Cookies.getCookie('rampart_token')||null;var subscriberToken=Cookies.getCookie('subscriber_token')||null;var utagData=window.utag_data||{};var isSwgPage=!!Cookies.getCookie('swg_sub_found');var authProviderRemap={facebook:'facebook.com',twitter:'twitter.com','google-oauth2':isSwgPage?'google.com swg':'google.com',linkedin:'linkedin.com',auth0:'auth0',};function getDefaultUserData(){var pc_memtype=utagData.pc_memtype||utagData.pcmemtype||'anonymous';return{think_id:'not set',authProvider:null,memType:pc_memtype,entitlementsResult:{entitlements:false,paywallCheck:false},};}
async function waitForRampartReady(){var maxAttempts=5;var interval=utagData.Jest_DEBUG_TIMEOUT||500;for(var i=0;i<maxAttempts;i++){var isReady=!!rampartToken||!!subscriberToken||typeof window.NLM?.user?.getProfile==='function'||typeof window.newscorpau?.rampart?.getLoginStatus==='function';if(isReady)return true;await new Promise(function(r){setTimeout(r,interval);});}
return false;}
async function waitForSubscriberToken(maxWaitMs,intervalMs){if(maxWaitMs===void 0)maxWaitMs=3000;if(intervalMs===void 0)intervalMs=200;var start=Date.now();return new Promise(function(resolve){(function check(){var token=Cookies.getCookie('subscriber_token');if(token)return resolve(token);if(Date.now()-start>=maxWaitMs)return resolve(null);setTimeout(check,intervalMs);})();});}
async function parseEntitlements(){var subsToken=Cookies.getCookie('subscriber_token')||null;if(!subsToken&&rampartToken)subsToken=await waitForSubscriberToken();if(subsToken){try{var entitlementsResult=JSON.parse(subsToken);var memType=entitlementsResult.entitlements?'subscriber':'registered';return{memType:memType,entitlementsResult:entitlementsResult};}catch(err){logger.error('Invalid subscriber token JSON',err);return{memType:'registered',entitlementsResult:{entitlements:false,paywallCheck:false}};}}
if(rampartToken)
return{memType:'registered',entitlementsResult:{entitlements:false,paywallCheck:false}};return{memType:'anonymous',entitlementsResult:{entitlements:false,paywallCheck:false}};}
function isValidJwt(token){if(!token||typeof token!=='string')return false;var parts=token.split('.');if(parts.length!==3)return false;try{var headerJson=atob(parts[0].replace(/-/g,'+').replace(/_/g,'/'));var payloadJson=atob(parts[1].replace(/-/g,'+').replace(/_/g,'/'));JSON.parse(headerJson);JSON.parse(payloadJson);return true;}catch{return false;}}
async function getProfileFromRampart(){var token=rampartToken||Cookies.getCookie('rampart_token');if(!token||!isValidJwt(token)){logger.info('No or invalid rampart token detected, returning default user data');return getDefaultUserData();}
var auth=getParsedJwt(token);var profile=auth['http://login.newscorpaustralia.com.au/profile']||{};var parsed=await parseEntitlements();var mappedAuth=authProviderRemap[profile.authProvider]||profile.authProvider||null;return{think_id:profile.think_id||'not set',authProvider:mappedAuth,memType:parsed.memType,entitlementsResult:parsed.entitlementsResult,};}
async function getUserMemtype(){var isReady=await waitForRampartReady();if(!isReady){logger.warn('Rampart Script not ready');var defaults=getDefaultUserData();window.utag_data=window.utag_data||{};window.utag_data.pc_memtype=defaults.memType;window.utag_data.pcsid=think_id||'not set';return{pcsid:defaults.think_id,memtype:defaults.memType,authProvider:defaults.authProvider,localStoragePCSID:null};}
var userData=getDefaultUserData();try{if(rampartToken){userData=await getProfileFromRampart();}else if(window.NLM?.user?.getProfile){userData=await window.NLM.user.getProfile();}else if(window.newscorpau?.rampart?.getLoginStatus){userData=await window.newscorpau.rampart.getLoginStatus();}}catch(err){logger.error('General error while fetching user data',err);}
var think_id=userData.think_id;var memType=userData.memType;if(/[0-9]/.test(think_id))Storage.setLocalStorageItem('metrics_pcsid',think_id);var localStoragePCSID=Storage.getLocalStorageItem('metrics_pcsid');logger.info('User Data',userData);window.utag_data=window.utag_data||{};window.utag_data.pc_memtype=memType;window.utag_data.pcsid=think_id;window.utag_data.authProvider=userData.authProvider;return{pcsid:think_id,memtype:memType,authProvider:userData.authProvider,localStoragePCSID:localStoragePCSID||null};}
getUserMemtype();})();})();}catch(e){console.log(e)}}catch(e){console.log(e);}
try{try{(function(){if(location.hostname.indexOf('supercoach.')!==-1)return;var w=window,wut=w.utag_data||{};var pageTypes=["index","recipe","homepage","collection","story","galleries","gallery","video","breach+shopfront","acq+shopfront"];var optimizelyScriptUrl="https://cdn.optimizely.com/js/20352597942.js",isShopfront=location.pathname.indexOf('subscribe/news/1')>-1;wut.net_content_type=wut.net_content_type||"";var contentTypeValue=wut.net_content_type.split("+");var matchFound=contentTypeValue.some(function(value){return pageTypes.includes(value);});function loadScriptAsync(src){return new Promise(function(resolve,reject){var script=document.createElement("script");script.type="text/javascript";script.src=src;script.onload=function(){resolve();};script.onerror=function(){reject(new Error("Failed to load script: "+src));};document.head.appendChild(script);});}
var includeToAllPagesBySite=function(){var allow=false;if(wut.net_site==='bodyandsoul'||wut.net_site==='escape'){allow=true;}
return allow;}
if(isShopfront||matchFound||includeToAllPagesBySite()){loadScriptAsync(optimizelyScriptUrl)
.then(function(){console.warn("Enabled Optimizely Script");})
.catch(function(error){console.error(error);});}})();}catch(e){console.log(e)}}catch(e){console.log(e);}
try{try{function getActiveOptimizelyTests(){if(!window.optimizely||typeof window.optimizely.get!=='function')return'';var state=window.optimizely.get('state');if(!state||typeof state.getCampaignStates!=='function')return'';var campaignStates=state.getCampaignStates(function(campaign){return campaign&&campaign.isActive;});var results=[];for(var campaignId in campaignStates){if(Object.prototype.hasOwnProperty.call(campaignStates,campaignId)){var campaign=campaignStates[campaignId];if(campaign&&campaign.isActive){var decision=state.getDecisionString({campaignId:campaignId});if(decision)results.push(decision);}}}
return results.join(';');}
(function(){if(location.hostname.indexOf('supercoach.')!==-1)return;var lastAbt;function updateDataLayers(){var abt=getActiveOptimizelyTests();if(!abt||abt===lastAbt)return;lastAbt=abt;window.utag_data=window.utag_data||{};window.utag_data.abt=abt;console.log('Active Optimizely Tests:',abt.split(';'));}
window.optimizely=window.optimizely||[];window.optimizely.push({type:'addListener',filter:{type:'lifecycle',name:'initialized'},handler:updateDataLayers});window.optimizely.push({type:'addListener',filter:{type:'lifecycle',name:'activated'},handler:updateDataLayers});updateDataLayers();var tries=0,maxTries=20;var poll=setInterval(function(){tries++;updateDataLayers();if(lastAbt||tries>=maxTries)clearInterval(poll);},250);})();}catch(e){console.log(e)}}catch(e){console.log(e);}
try{try{var ud=window.utag_data||{};var isGdprUser=(ud.gdpr_user===true||ud.gdpr_user==="true");var isTTB=(ud.net_site==="ttb");if(isGdprUser&&isTTB){ud.disable_ads=true;}}catch(e){console.log(e)}}catch(e){console.log(e);}